-- ==========================================================
-- Module: 4.3 Communication Service
-- File: 01_create_email_events.sql
-- Description:
-- Stores all email communication events generated by the system.
-- Team 2 integration (lead_id foreign key) will be added later.
-- ==========================================================

CREATE TABLE email_events (

    -- Unique identifier for each email event
    event_id UUID PRIMARY KEY,

    -- Lead identifier from Team 2
    -- TODO: Add FOREIGN KEY after Team 2 schema is finalized
    lead_id UUID NOT NULL,

    -- Type of email event
    event_type VARCHAR(30) NOT NULL CHECK (
        event_type IN (
            'SENT','DELIVERED','OPENED','CLICKED','REPLIED','BOUNCED',
            'COMPLAINT','DEFERRED','REJECTED'
        )
    ),

    -- Email service provider
    email_provider VARCHAR(30) NOT NULL,

    -- Message ID returned by the email provider
    provider_message_id VARCHAR(255),

    -- Additional event information
    event_details TEXT,

    -- Time when the event occurred
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP

);

-- ==========================================================
-- TODO
-- ==========================================================
-- 1. Add FOREIGN KEY (lead_id) REFERENCES leads(lead_id)
--    after Team 2 schema is finalized.
--
-- 2. Verify supported event types with AWS SES/Nodemailer.
--
-- 3. Add indexes after table creation.
-- ==========================================================| Event         | Meaning                                   |
| ------------- | ----------------------------------------- |
| **SENT**      | Email sent successfully                   |
| **DELIVERED** | Email reached the recipient's mail server |
| **OPENED**    | Recipient opened the email                |
| **CLICKED**   | Recipient clicked a link in the email     |
| **REPLIED**   | Recipient replied to the email            |
| **BOUNCED**   | Email could not be delivered              |
| **COMPLAINT** | Recipient marked the email as spam        |
| **DEFERRED**  | Delivery was temporarily delayed          |
| **REJECTED**  | Email was rejected before delivery        |
